In [1]:
import numpy as np
def check_constraint(x, capacity, weight):
    chosen_bin = compute_fitness(x)
    if chosen_bin == 0:
        return False   
    remaining = [capacity] * chosen_bin    
    if remaining[0] < weight[0]:
        return False
    
    remaining[0] -= weight[0]
    i = 0
    for j in range(1, len(weight)):
        
        if (remaining[i] - weight[j] >= 0):
            remaining[i] -= weight[j]
            i = 0
        else:
            i +=1
            if i == chosen_bin:
                return False
            j -= 1
    return True
def compute_fitness(bin):
    return np.sum(bin)

def compute_val_fitness(bin):
    if (check_constraint(real2bin(bin),c, weight) == True):
        return compute_fitness(bin)
    else:
        return 0
    

def real2bin(x):
    sigmoid_values = 1 / (1 + np.exp(-x))
    binary_values = np.where(sigmoid_values >= 0.5, 1, 0)
    return binary_values

def normalize_array(arr):
    norm = np.amax(arr)
    normalized_arr = arr / norm
    return normalized_arr
# Driver program
weight = [42, 69, 67, 57, 93, 90, 38, 36, 45, 42, 33, 79, 27, 57, 44, 84, 86, 92, 46, 38, 85,
33, 82, 73, 49, 70, 59, 23, 57, 72, 74, 69, 33, 42, 28, 46, 30, 64, 29, 74, 41, 49, 55, 98, 80, 32, 25, 38,
82, 30, 35, 39, 57, 84, 62, 50, 55, 27, 30, 36, 20, 78, 47, 26, 45, 41, 58, 98, 91, 96, 73, 84, 37, 93, 91,
43, 73, 85, 81, 79, 71, 80, 76, 83, 41, 78, 70, 23, 42, 87, 43, 84, 60, 55, 49, 78, 73, 62, 36, 44, 94, 69,
32, 96, 70, 84, 58, 78, 25, 80, 58, 66, 83, 24, 98, 60, 42, 43, 43, 39, 97, 57, 81, 62, 75, 81, 23, 43, 50,
38, 60, 58, 70, 88, 36, 90, 37, 45, 45, 39, 44, 53, 70, 24, 82, 81, 47, 97, 35, 65, 74, 68, 49, 55, 52, 94,
95, 29, 99, 20, 22, 25, 49, 46, 98, 59, 98, 60, 23, 72, 33, 98, 80, 95, 78, 57, 67, 53, 47, 53, 36, 38, 92,
30, 80, 32, 97, 39, 80, 72, 55, 41, 60, 67, 53, 65, 95, 20, 66, 78, 98, 47, 100, 85, 53, 53, 67, 27, 22, 61,
43, 52, 76, 64, 61, 29, 30, 46, 79, 66, 27, 79, 98, 90, 22, 75, 57, 67, 36, 70, 99, 48, 43, 45, 71, 100, 88,
48, 27, 39, 38, 100, 60, 42, 20, 69, 24, 23, 92, 32 ];
c = 150
nVars = len(weight)


In [2]:
#x=np.array([1,1,0,0,0])
#check_constraint(x, c, weight)

In [3]:
#parámetros
pop_size=20
a_factor=6 #valor que oscila entre [5,10]
R_factor=1.5
alpha=1.5 #valor que oscila entre [1.5-2]
low=0 #espacio de busqueda bajo
high=1 #espacio de busqueda alto
c1=2
c2=2
maxIter=1000

In [4]:
#inicializamos la población como valores aleatorios entre 0 y 1
x=[]
for i in range(0,pop_size,1):
    x.append(np.random.uniform(0, 1, nVars))
x=np.array(x)
print(x)


[[0.02812782 0.67038741 0.09610295 ... 0.52210254 0.23237637 0.75793454]
 [0.04018462 0.34413551 0.1659657  ... 0.40453207 0.26349457 0.33912598]
 [0.99550774 0.78683524 0.14492549 ... 0.8795655  0.77000708 0.06173607]
 ...
 [0.08007391 0.30749393 0.76723573 ... 0.61957911 0.29882989 0.24791919]
 [0.83376566 0.30585772 0.00449764 ... 0.24613399 0.0616612  0.66543589]
 [0.25043536 0.31829157 0.27203265 ... 0.70550382 0.57261359 0.76985203]]


## Select space eq
$P_{new}=P_{best}+{\alpha}r(P_{mean}-P_{i})$

In [5]:
#select space
#inicializamos P_Best como el peor caso
P_best = np.ones(nVars)
P_new = np.zeros(nVars)
for i in x:
    for j in range(0,len(i),1):
        P_new[j] = low + alpha*np.random.rand()*(np.mean(i)-i[j])
    #P_new=normalize_array(P_new)
    if (check_constraint(real2bin(P_new),c, weight) == True):
        if(compute_fitness(real2bin(P_new))<compute_fitness(real2bin(i)) and check_constraint(real2bin(i),c, weight) == True):
            i=P_new
        if(compute_fitness(real2bin(i))<compute_fitness(real2bin(P_best))):
            P_best=i

print(check_constraint(real2bin(P_best), c, weight))
print(compute_fitness(real2bin(P_best)))
print(P_best)
print(real2bin(P_best))

        

True
124
[ 0.31749214  0.08581893  0.17699029  0.25012393  0.10064605  0.0673776
  0.49783745 -0.28859563 -0.01698762 -0.57913035  0.10857825 -0.01918321
  0.06868563 -0.01644978  0.04336765 -0.42624844  0.36207359 -0.10949783
  0.01882977 -0.11478792 -0.43713706 -0.23631851  0.2969087   0.00857161
  0.15387119 -0.6240254   0.04820881 -0.58042741 -0.18338978  0.0025025
 -0.08232348 -0.18379853  0.0241242  -0.58333707 -0.23945331 -0.23116932
  0.21303207  0.12649636  0.09940733  0.06873725 -0.03685295 -0.35087951
  0.21562607 -0.16550043  0.05110996 -0.01047124 -0.12530573 -0.16868295
 -0.13209437  0.32835756 -0.50198278 -0.087953    0.21891232  0.27566718
  0.02007116  0.22321752  0.43298836 -0.34450204  0.5098068  -0.40355463
  0.11674953  0.2800002   0.1060297  -0.09725638  0.63566367  0.01272342
 -0.17073387 -0.08817497 -0.15413517  0.40895531 -0.2210219  -0.02326998
  0.20096176  0.13495189  0.28445673  0.20641856  0.26100077 -0.09741791
  0.01575874  0.37193662 -0.07667808  0.0184

## Search in space eq
$P_{new}=P_{i}+y(i)(P_{i}-P_{i+1})+x(i)(P_{i}-P_{mean})$

In [6]:
#search stage
def create_x_y_x1_y1__():
    #Using numpy vector for faster computational time
    ## Eq. 2
    phi = a_factor * np.pi * np.random.uniform(0, 1, nVars)
    r = phi + R_factor * np.random.uniform(0, 1, nVars)
    xr, yr = r * np.sin(phi), r * np.cos(phi)

    ## Eq. 3
    r1 = phi1 = a_factor * np.pi * np.random.uniform(0, 1, nVars)
    xr1, yr1 = r1 * np.sinh(phi1), r1 * np.cosh(phi1)

    x_list = xr / np.max(xr)
    y_list = yr / np.max(yr)
    x1_list = xr1 / np.max(xr1)
    y1_list = yr1 / np.max(yr1)
    return x_list, y_list, x1_list, y1_list

In [7]:
P_new = np.zeros(nVars)
for i in range(0,pop_size,1):
    x_list, y_list, x1_list, y1_list = create_x_y_x1_y1__() #generamos valores aleatorios por el tamaño de pop size
    for j in range(0,len(P_best),1):
        if (j!=len(P_best)-1):
            P_new[j]=P_best[j]+y_list[j]*(P_best[j]-P_best[j+1])+x_list[j]*(P_best[j]-np.mean(P_best))
        else:
            P_new[j]=P_best[j]+y_list[j]*(P_best[j]-P_best[-1])+x_list[j]*(P_best[j]-np.mean(P_best))
    P_new=normalize_array(P_new)
    if (check_constraint(real2bin(P_new),c, weight) == True):
        if(compute_fitness(real2bin(P_new))<compute_fitness(real2bin(P_best))):
            P_best=P_new
print(check_constraint(real2bin(P_best), c, weight))
print(compute_fitness(real2bin(P_best)))
print(P_best)
print(real2bin(P_best))

True
96
[ 9.40335656e-04 -1.32057626e-02  1.71663656e-01  5.47254247e-01
 -1.23638092e-02  5.99638894e-02 -8.56930112e-02 -4.37105034e-01
 -6.29715934e-01 -6.36882328e-03 -5.58475489e-04 -6.14617088e-03
 -7.02844124e-03 -6.85067354e-03 -3.56459177e-02 -3.56283150e-02
 -1.80306431e-01  3.82613847e-02 -6.33679630e-03 -8.85317440e-03
  5.89583390e-03 -4.50633539e-02 -8.93169510e-03  4.99403981e-02
 -2.25666298e-02  5.81904964e-02  3.97766551e-02 -1.51713653e-02
  3.51694189e-03  2.77962353e-02  7.36713488e-03  3.06369333e-02
 -1.21412693e-02 -4.65288208e-02  2.47634097e-03  6.10281530e-04
  6.30370341e-02  8.52863180e-02  2.87343348e-02 -6.75195674e-02
  1.18786595e-02 -2.81511240e-03 -6.25075302e-03  3.00188058e-02
 -1.34232862e-02  1.20992982e-01 -5.29585325e-03  1.18139874e-02
  3.10553913e-02  2.33339710e-03  3.98609385e-03 -1.79718591e-02
  1.00273855e-01 -1.00677848e-01  6.66449931e-04 -8.24640855e-03
 -4.92417746e-03 -1.88830486e-02 -1.05814354e-02  1.36738858e-02
  1.27136817e-02 

## Swoop
$P_{new}=randP_{best}+x1(i)(P_{i}-c1P_{mean})+y1(i)(P_{i}-c2P_{best})$

In [8]:
P_new = np.zeros(nVars)
for i in range(0,pop_size,1):
    x_list, y_list, x1_list, y1_list = create_x_y_x1_y1__()
    for j in range(0,len(P_best),1):
        P_new[j]=np.random.rand()*compute_fitness(real2bin(P_best))+x1_list[j]*(P_best[j]-c1*np.mean(P_best))+y1_list[j]*(P_best[j]-c2*compute_fitness(real2bin(P_best)))
    P_new=normalize_array(P_new)
    
    if (check_constraint(real2bin(P_new),c, weight) == True):
        if(compute_fitness(real2bin(P_new))<compute_fitness(real2bin(P_best))):
            print(P_new)
            P_best=P_new
print(check_constraint(real2bin(P_best), c, weight))
print(compute_fitness(real2bin(P_best)))
print(P_best)
print(real2bin(P_best))

True
96
[ 9.40335656e-04 -1.32057626e-02  1.71663656e-01  5.47254247e-01
 -1.23638092e-02  5.99638894e-02 -8.56930112e-02 -4.37105034e-01
 -6.29715934e-01 -6.36882328e-03 -5.58475489e-04 -6.14617088e-03
 -7.02844124e-03 -6.85067354e-03 -3.56459177e-02 -3.56283150e-02
 -1.80306431e-01  3.82613847e-02 -6.33679630e-03 -8.85317440e-03
  5.89583390e-03 -4.50633539e-02 -8.93169510e-03  4.99403981e-02
 -2.25666298e-02  5.81904964e-02  3.97766551e-02 -1.51713653e-02
  3.51694189e-03  2.77962353e-02  7.36713488e-03  3.06369333e-02
 -1.21412693e-02 -4.65288208e-02  2.47634097e-03  6.10281530e-04
  6.30370341e-02  8.52863180e-02  2.87343348e-02 -6.75195674e-02
  1.18786595e-02 -2.81511240e-03 -6.25075302e-03  3.00188058e-02
 -1.34232862e-02  1.20992982e-01 -5.29585325e-03  1.18139874e-02
  3.10553913e-02  2.33339710e-03  3.98609385e-03 -1.79718591e-02
  1.00273855e-01 -1.00677848e-01  6.66449931e-04 -8.24640855e-03
 -4.92417746e-03 -1.88830486e-02 -1.05814354e-02  1.36738858e-02
  1.27136817e-02 